# -*- coding: utf-8 -*-
"""jan23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VA0n0G_qYo4C29vitj69Rmq7oBt14UAY
"""

a=int(input())
b=int(input())
c=int(input())
if(a>b and a>c):
  print(a,"is greatest")
elif(b>a and b>c):
  print(b,"is greatest")
else:
  print(c,"is greatest")

a,b,c=input().split(" ")
if(a>b and a>c):
  print(a,"is greatest")
elif(b>a and b>c):
  print(b,"is greatest")
else:
  print(c,"is greatest")

for i in range(5):
  print(i)

n=int(input("enter no of rows:"))
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end="  ")
  print()

n=int(input("enter no of rows:"))
for i in range(1,n+1):
  for j in range(1,i+1):
    print("*",end="  ")
  print()

n=int(input("enter a number:"))
fact=1
for i in range(1,n+1):
  fact=fact*i
print("factorial of",n,"is",fact)

n=int(input())
first=0
second=1
if(n<=0):
  print("invalid input")
elif(n==1):
  print(first)  
else:
  print(first,second,end=" ")
  for i in range(2,n):
    next=first+second
    print(next,end=" ")
    first=second
    second=next

n=int(input("enter the number:"))
if(n>1):
  for i in range(2,n):
    if(n%i==0):
      print("given number is not prime")
      break
  else:
      print("the given number is prime")

tup=[1,2,3,4,5,6]
sum=0
for i in tup:
  sum=sum+i
avg=sum/len(tup)
print("average:")

List=input().split()
l=[int(i) for i in List]
e=[]
o=[]
ze=[]
for i in l:
  if(i==0):
    ze.append(i)
  elif(i%2==0):
    e.append(i)
  else:
    o.append(i)
print(e)
print(o)
print(ze)

string=input()
q=len(string)
if(q%4==0):
  print("".join(reversed(string)))
else:
  print("not poosible")

