# -*- coding: utf-8 -*-
"""jan30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzRQLSZUBvrzR0rWcXxtAHcHzREhJfXc
"""

class student:
  name="Random name"
  rollnumber=100
obj=student()
print(obj.name)
print(obj.rollnumber)

class student:
  name="Random name"
  __rollnumber=100
  def get_rollnumber(self):
    return self.__rollnumber
  def set_rollnumber(self,new_value):
    self.__rollnumber=new_value 

obj=student()
print(obj.name)
print(obj.set_rollnumber(200))  
print(obj.get_rollnumber())

class A:
  def method_1(self):
    print("in class A")
class B:
  def method_1(self):
    print("in class B")
class child(B,A):

n=int(input())
arr=[]
for i in range(n):
  username=input("username:")
  password=input("password:")
  arr.append({username: password})

print(arr)

x=input()
l=len(x)
lst=[]
for letter in x:
  lst.append(letter)
for i in range(l):
  if(i%2==0):
    print(lst[i],end=" ")

n=int(input())
arr=[]
for i in range(n):
  username=input("username:")
  password=input("password:")
  arr.append({username: password})

print(arr)  
u1=input("enter username:")
p1=input("enter password:")
found=False
for obj in arr:
  try:
    password=obj[u1]
    found=True
    if p1==password:
      print("valid password")
    else:
      print("invalid password")
  except:
    pass  
if found==False:
  print("user not found")

stack=[]
stack.append(1)
stack.append(2)
stack.append(3)
stack.append(4)
stack.append(5)
print(stack)
stack.pop()
print(stack)

queue=[]
queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)
queue.append(5)
print(queue)
queue.pop(0)
print(queue)

import random
player=input("choose from choice:")
com=random.randint(0,2)
choice=['rock','paper','scissor']

if player==rock and com==rock:
  print("tie")
elif player==paper and com==rock:
    print("player wins")
elif player==rock and com==scissor:
    print("player wins")
elif player==scissor and com==paper:
  print("player wins")
else:
  print("computer wins")

import random
n=input("Enter your choice:")
l=["Rock","Paper","Scissors"]
s=random.choice(l)
print("Computer choice",s)
if n=="Rock" or n=="rock":
    if s=="Scissors" or s=="scissors":
        print("Player won")
    elif s=="Rock" or s=="rock":
        print("DRAW")
    else:
        print("Computer won")
elif n=="Scissors" or n=="scissors":
    if s=="Paper" or s=="paper":
        print("Player won")
    elif s=="Scissors" or s=="scissors":
        print("DRAW")
    else:
        print("Computer won")
elif n=="Paper" or n=="paper":
    if s=="Rock" or s=="rock":
        print("Player won")
    elif s=="Paper" or s=="paper":
        print("DRAW")
    else:
        print("Computer won")
else:
    print("INVALID INPUT")

import random
player=0
computer=0
for i in range(100):
  n=input("Enter your choice:")
  l=["Rock","Paper","Scissors"]
  s=random.choice(l)
  print("Computer choice",s)
  if n=="Rock" or n=="rock":
      if s=="Scissors" or s=="scissors":
          print("Player won")
          player+=1
      elif s=="Rock" or s=="rock":
          print("DRAW")
      else:
          print("Computer won")
          computer+=1
  elif n=="Scissors" or n=="scissors":
      if s=="Paper" or s=="paper":
          print("Player won")
          player+=1
      elif s=="Scissors" or s=="scissors":
          print("DRAW")
      else:
          print("Computer won")
          computer+=1
  elif n=="Paper" or n=="paper":
      if s=="Rock" or s=="rock":
          print("Player won")
          player+=1
      elif s=="Paper" or s=="paper":
          print("DRAW")
      else:
          print("Computer won")
          computer+=1
  else:
      print("INVALID INPUT")
  if(player==5):
    print("player won")
    break
  elif(computer==5):
    print("computer won")
    break

