# -*- coding: utf-8 -*-
"""jan30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzRQLSZUBvrzR0rWcXxtAHcHzREhJfXc
"""

class student:
  name="Random name"
  rollnumber=100
obj=student()
print(obj.name)
print(obj.rollnumber)

class student:
  name="Random name"
  __rollnumber=100
  def get_rollnumber(self):
    return self.__rollnumber
  def set_rollnumber(self,new_value):
    self.__rollnumber=new_value 

obj=student()
print(obj.name)
print(obj.set_rollnumber(200))  
print(obj.get_rollnumber())

class A:
  def method_1(self):
    print("in class A")
class B:
  def method_1(self):
    print("in class B")
class child(B,A):

n=int(input())
arr=[]
for i in range(n):
  username=input("username:")
  password=input("password:")
  arr.append({username: password})

print(arr)

x=input()
l=len(x)
lst=[]
for letter in x:
  lst.append(letter)
for i in range(l):
  if(i%2==0):
    print(lst[i],end=" ")

n=int(input())
arr=[]
for i in range(n):
  username=input("username:")
  password=input("password:")
  arr.append({username: password})

print(arr)  
u1=input("enter username:")
p1=input("enter password:")
found=False
for obj in arr:
  try:
    password=obj[u1]
    found=True
    if p1==password:
      print("valid password")
    else:
      print("invalid password")
  except:
    pass  
if found==False:
  print("user not found")

stack=[]
stack.append(1)
stack.append(2)
stack.append(3)
stack.append(4)
stack.append(5)
print(stack)
stack.pop()
print(stack)

queue=[]
queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)
queue.append(5)
print(queue)
queue.pop(0)
print(queue)

